services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: notification-bot
      WATCHTOWER_POLL_INTERVAL: 3600

  notification-bot:
    container_name: notification-bot
    hostname: notification-bot
    image: docker-registry.markridgwell.com/credfeto/notification-bot:latest
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    volumes:
      - ./appsettings-local.json:/usr/src/app/appsettings-local.json:r
