---
services:
  notification-bot:
    container_name: notification-bot
    hostname: notification-bot
    image: docker-registry.markridgwell.com/credfeto/notification-bot:latest
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./notification/appsettings-local.json:/usr/src/app/appsettings-local.json:ro

  dispatcher-bot:
    container_name: dispatcher-bot
    hostname: dispatcher-bot
    image: docker-registry.markridgwell.com/credfeto/dispatcher-bot:latest
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./dispatcher/appsettings-local.json:/usr/src/app/appsettings-local.json:ro
      - ./certs/dispatcher.pfx:/usr/src/app/server.pfx:ro

  github-api-proxy:
    container_name: github-api-proxy
    hostname: github-api-proxy
    image: docker-registry.markridgwell.com/credfeto/github-api-proxy:latest
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    security_opt:
      - no-new-privileges:true
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - CREDENTIALS_FILE=/proxy/credentials.json
      - PORT=3000
    volumes:
      - ./proxy/credentials.json:/proxy/credentials.json:ro

volumes:
  dispatcher-data:
    external: true
    name: dispatcher-data
