services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: notification-bot
      WATCHTOWER_POLL_INTERVAL: 60

  notification-bot:
    container_name: notification-bot
    hostname: notification-bot
    image: docker-registry.markridgwell.com/credfeto/notification-bot:latest
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    volumes:
      - ./notification/appsettings-local.json:/usr/src/app/appsettings-local.json:r

  dispatcher-bot:
    container_name: dispatcher-bot
    hostname: dispatcher-bot
    image: docker-registry.markridgwell.com/credfeto/dispatcher-bot:latest
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./dispatcher/appsettings-local.json:/usr/src/app/appsettings-local.json:r
      - dispatcher-data:/usr/src/app/data
      - ./certs/dispatcher.pfx:/usr/src/app/server.pfx:ro

  github-api-proxy:
    container_name: github-api-proxy
    hostname: github-api-proxy
    image: docker-registry.markridgwell.com/credfeto/github-api-proxy:latest
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - CREDENTIALS_FILE=/proxy/credentials.json
      - PORT=3000
    volumes:
      - ./proxy/credentials.json:/proxy/credentials.json:ro

volumes:
  dispatcher-data:
    external: true
    name: dispatcher-data
